services:
  nexus:
    image: sonatype/nexus3:3.92.0
    container_name: nexus
    restart: unless-stopped
    user: "200:200"
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    depends_on:
      - apk-auth-proxy

  apk-auth-proxy:
    image: nginx:stable-alpine
    container_name: apk-auth-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Pull token from: chainctl auth pull-token create --repository=apk --parent=$ORGNAME
      CHAINGUARD_APK_AUTH: "${CHAINGUARD_APK_AUTH}"
      CHAINGUARD_APK_ORG: "${CHAINGUARD_APK_ORG}"
    volumes:
      - ./nginx:/etc/nginx/templates:ro

volumes:
  nexus-data:
